name: Testing 

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches:    
  #     - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v3
      - name: 'Install dependencies'
        run: npm install
      - name: 'Test code'
        run: npm test
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v3
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

